# Generated by Django 5.0.2 on 2024-04-27 03:07

import django.core.validators
import django.db.models.deletion
import storages.backends.s3
import whistleblower.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.CharField(default='N/A', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('appealed', 'Appealed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=whistleblower.models.create_new_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'docx'])])),
                ('publication_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Published', 'Published'), ('Denied', 'Denied')], default='In Progress', max_length=20)),
                ('appear_anonymous', models.BooleanField(default=False)),
                ('downvotes', models.ManyToManyField(default=0, related_name='downvoted_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(default=0, related_name='upvoted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to=whistleblower.models.create_new_file_name)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whistleblower.report')),
            ],
        ),
    ]
